---
- hosts: pfservers
  name: install pf on standalones
  become: True
  roles:
    - role: packetfence_common
      tags: install
    - role: packetfence_install
      tags: install

# fixme
# - import_playbook: playbooks/deploy-inverse-support.yml
#   tags: support

# TODO
# upgrade OS
# utils

# specific to centos
- import_playbook: playbooks/set-ip-addresses.yml
  tags: network
  
- import_playbook: playbooks/set-time.yml
  tags: time

# postconfig
- import_playbook: playbooks/postconfig.yml
  tags: postconfig

# monit
# - import_playbook: playbooks/deploy-monit.yml
#   tags: monit

# maintenance patches
- import_playbook: playbooks/maintenance.yml
  tags: maintenance

