---
# Specific to centos  
- import_playbook: playbooks/set-time.yml
  tags: time

- import_playbook: playbooks/set-ip-addresses.yml
  tags: network

- hosts: pfservers
  name: install pf on standalones
  become: True
  roles:
    - role: inverse_inc.packetfence.packetfence_common
      tags: install
    - role: inverse_inc.packetfence.packetfence_install
      tags: install

# fixme
# - import_playbook: playbooks/deploy-inverse-support.yml
#   tags: support

# TODO
# upgrade OS
# utils

# postconfig
- import_playbook: playbooks/postconfig.yml
  tags: postconfig

- import_playbook: playbooks/nullmailer.yml
  tags: nullmailer

# monit
# - import_playbook: playbooks/deploy-monit.yml
#   tags: monit

# maintenance patches
- import_playbook: playbooks/maintenance.yml
  tags: maintenance

