---
timesync_ntp_servers:
  - hostname: 0.centos.pool.ntp.org
    iburst: yes
  - hostname: 1.centos.pool.ntp.org
    iburst: yes
  - hostname: 2.centos.pool.ntp.org
    iburst: yes
  - hostname: 3.centos.pool.ntp.org
    iburst: yes
timezone: Europe/Paris

smtp_server: ''
  
packetfence_install__centos_packages:
  - packetfence-9.2.0

packetfence_install__deb_packages:
  - packetfence=9.2.0
  
packetfence_install__mgmt_interface:
  id: "{{ ansible_default_ipv4['interface'] }}"
  ip: "{{ ansible_default_ipv4['address'] }}"
  mask: "{{ ansible_default_ipv4['netmask'] }}"
  type: management,portal

# packetfence_install__config_base_general:
#   hostname: "{{ ansible_distribution|lower }}"
#   domain: example.lan
#   dhcpservers: 10.0.0.1,192.168.122.1
#   timezone: "{{ timezone }}"
# packetfence_install__config_base_alerting:
#   smtpserver: localhost
#   fromaddr: "{{ packetfence_install__config_base_general['hostname'] }}@{{ packetfence_install__config_base_general['domain'] }}"
#   emailaddr: alerting@inverse.ca
#   smtp_port: 1025
#   smtp_verifyssl: disabled
#   subjectprefix: PF UNDER TEST
#   smtp_timeout: 30
# packetfence_install__config_base_advanced:
#   hash_passwords: ntlm
# packetfence_install__sources:
#   - id: Blackhole
#     description: Blackhole
#     type: Blackhole


# packetfence_install__api_calls:
#   - route: "{{ packetfence_install__api_config_endpoints['base'] }}/general"
#     method: PATCH
#     body:
#       id: general
#       dhcpservers: "{{ packetfence_install__config_base_general['dhcpservers'] }}"
#       domain: "{{ packetfence_install__config_base_general['domain'] }}"
#       hostname: "{{ packetfence_install__config_base_general['hostname'] }}"
#       timezone: "{{ packetfence_install__config_base_general['timezone'] }}"
#   - route: "{{ packetfence_install__api_config_endpoints['base'] }}/alerting"
#     method: PATCH
#     body:
#       id: alerting
#       smtpserver: "{{ packetfence_install__config_base_alerting['smtpserver'] }}"
#       fromaddr: "{{ packetfence_install__config_base_alerting['fromaddr'] }}"
#       emailaddr: "{{ packetfence_install__config_base_alerting['emailaddr'] }}"
#       smtp_port: "{{ packetfence_install__config_base_alerting['smtp_port'] }}"
#       smtp_verifyssl: "{{ packetfence_install__config_base_alerting['smtp_verifyssl'] }}"
#       subjectprefix: "{{ packetfence_install__config_base_alerting['subjectprefix'] }}"
#       smtp_timeout: "{{ packetfence_install__config_base_alerting['smtp_timeout'] }}"
#   - route: "{{ packetfence_install__api_config_endpoints['fingerbank_setting'] }}/upstream"
#     method: PATCH
#     body:
#       id: upstream
#       api_key: "{{ packetfence_install__config_fingerbank_setting_upstream['api_key'] }}"
#   - route: "{{ packetfence_install__api_config_endpoints['base'] }}/advanced"
#     method: PATCH
#     body:
#       id: advanced
#       hash_passwords: "{{ packetfence_install__config_base_advanced['hash_passwords'] }}"
