---
packetfence_install__centos_packages:
  - packetfence-9.3.0

packetfence_install__deb_packages:
  - packetfence=9.3.0
  
packetfence_install__mgmt_interface:
  id: "{{ ansible_default_ipv4['interface'] }}"
  ip: "{{ ansible_default_ipv4['address'] }}"
  mask: "{{ ansible_default_ipv4['netmask'] }}"
  type: management,portal

packetfence_install__alerting_emailaddr: 'pf@localhost'

packetfence_install__configuration:

      - name: 'pf.conf'
        sections:

          - name: 'general'
            settings:

              - name: 'domain'
                value: '{{ ansible_domain }}'

              - name: 'hostname'
                value: 'nac'

              - name: 'timezone'
                value: "{{ ansible_date_time['tz'] }}"

          - name: 'alerting'
            settings:

              - name: 'emailaddr'
                value: '{{ packetfence_install__alerting_emailaddr }}'


          - name: 'database'
            settings:

              - name: 'pass'
                value: '{{ packetfence_install__database_pass }}'

          - name: 'advanced'
            settings:

              - name: 'configurator'
                value: '{{ packetfence_install__configurator_status }}'

              - name: 'hash_passwords'
                value: 'ntlm'

          - name: "interface {{ packetfence_install__mgmt_interface['id'] }}"
            settings:

              - name: 'ip'
                value: "{{ packetfence_install__mgmt_interface['ip'] }}"

              - name: 'mask'
                value: "{{ packetfence_install__mgmt_interface['mask'] }}"

              - name: 'type'
                value: "{{ packetfence_install__mgmt_interface['type'] }}"

      - name: 'pfconfig.conf'
        sections:

          - name: 'general'
            settings:

              - name: 'backend'
                value: 'mysql'

          - name: 'mysql'
            settings:

              - name: 'host'
                value: 'localhost'

              - name: 'user'
                value: '{{ packetfence_install__database_default_user }}'

              - name: 'pass'
                value: '{{ packetfence_install__database_pass }}'

              - name: 'db'
                value: '{{ packetfence_install__database_db }}'

              - name: 'port'
                value: '3306'

              - name: 'table'
                value: 'keyed'

